# Generated by Django 2.2.6 on 2020-02-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfortutor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='requestfortutor',
            name='data_origin',
            field=models.CharField(choices=[('old', 'old'), ('new', 'new')], default='new', max_length=255, verbose_name='data origin'),
        ),
        migrations.AlterField(
            model_name='requestfortutor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='tuitionrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='tuitionrequest',
            name='data_origin',
            field=models.CharField(choices=[('old', 'old'), ('new', 'new')], default='new', max_length=255, verbose_name='data origin'),
        ),
        migrations.AlterField(
            model_name='tuitionrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
